### ISSUE TITLE
Plants testing

### ISSUE THREAD

**Issue by ancientmarinerdev** [ChefZander/skyblock_zero#41]
This is fun, and I love watching the algae and moss grow. I like the way it is challenging to set up plant growing, but it's doable.

I really like the concept of pyrograss, and maybe I've missed this, but it could be more of a consumable also.

My initial testing has the following feedback:

- [ ] It is not clear that moss only grows on matter blobs. It should probably grow on reinforced matter blobs too or any hard surface. It's a lifeform growing out of water, so it shouldn't matter too much what it grows on.
- [ ] Using matter annihilator for farming is suffering. It is desperately long overdue to get new tools that can dig algae and moss. Maybe a titanium shovel or something with MUCH better durability.
- [ ] CO2 balance is a bit off. A burner should provide more than for 1 plant. I think it should probably provide for 10 plants so if you have a 3 by 3 farm, it'll only need 1 burner.
- [ ] Burner should take longer to burn through green materials. It takes a lot longer to dig than before it's burnt through stuff for 1 plant. It should last probably 5 times longer.
- [ ] There is no reasonable way of automating gathering of organic matter. The node breaker which doesn't seem to be useful for anything but this so far takes 50 energy. That is 50 solar panels. If I want to automate a farm with 10 of these by a pond, it would take 500 energy, or 500 solar panels. That's painfully over the the top. It could arguably take 10-15, so to power 10, you need 100-150 solar panels. It still feels too much. 70 is probably more reasonable. Maybe even 50, so doubt the sized farm takes 100. So maybe they should use 5 power each. As you can see, balance is well off, and when there is no real functional benefit for these yet other than this, it really is the first main use case

As I play more, I can add more to this.

**Comment by theidealist101** [comment]
- Yeah I suppose adding moss growth on reinforced matter would be a good idea since the meteorites and stuff are encouraging people to build with it. Perhaps other things like the solid side of slabs as well.
- We definitely need a better tool for mining stuff, I agree.
- Different plants are worth different amounts of CO2 in the burner, I suppose I didn't clarify that. Moss and algae are the worst, pyrograss is the best.
- You could try using better fuels as stated above, since excess CO2 is stored. (I'm also planning a sort of detector which would output a different amount of power based on how full things are, like Minecraft comparators. If I made it so it detected the atmospheric CO2 in the habitat regulator, that could allow you to, say, only fuel the burner when it gets low?)
- Use generators instead of solar panels? The core dust could come from a puncher, and if the puncher takes more power than it can supply then that's definitely a balancing issue. I think more power-producing things would be useful too, perhaps coming from this stuff I could add some sort of biomass power generator?

**Comment by TheEt1234** [comment]
1) done
2) done
3) todo
4) i think colorium tree logs take longer to burn, ill see
5) using solar panels for node breakers is kinda ridicilous, use emittrium reactors instead

**Comment by TheEt1234** [comment]
Soo... turns out...

Some things burn a lot stronger in the burner, i didn't know this

I still don't like that, because i think its better if they could choose to burn for longer instead, so yeah, that's what ill do

**Comment by TheEt1234** [comment]
Alr no i actually didnt get the co2 system at first, now i get it...

The burner is fine as-is, just needs some more explaining

>  Burner should take longer to burn through green materials. It takes a lot longer to dig than before it's burnt through stuff for 1 plant. It should last probably 5 times longer.

This does not matter at all, the co2 gets stored in the habitat

**Comment by TheEt1234** [comment]
so, with my PR that explains things better, this should be solved

**Comment by ancientmarinerdev** [comment]
> 1. done
> 
>     2. done
> 
>     3. todo
> 
>     4. i think colorium tree logs take longer to burn, ill see
> 
>     5. using solar panels for node breakers is kinda ridiculous, use emittrium reactors instead, but good point, i will half their power cost (along with deployers)

Appreciate you taking the time to look into it. I haven't retested it, but I'm sure it's lots better :).
